### ISSUE TITLE
Issue building with latest "0.17.0"

### ISSUE THREAD

**Issue by JakeKalstad** [guillaume-be/rust-bert#245]
I'm unable to build using `rust-bert = "0.17.0"`

Removing rust-bert and trying to include `torch-sys v0.7.0` is building but when I try to include latest rust-bert I get met with the following error after building with cargo. 

I've downloaded and extracted `libtorch-shared-with-deps-1.11.0+cu113.zip` into a directory and pointed all the env vars to it
rustc 1.62.0-nightly
cargo 1.62.0-nightly
ubuntu 21.10
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

error: failed to run custom build command for `torch-sys v0.6.1`

Caused by:
  process didn't exit successfully: `/xxx/target/debug/build/torch-sys-19553a5e993180b5/build-script-build` (exit status: 127)
  --- stderr
  /xxx/target/debug/build/torch-sys-19553a5e993180b5/build-script-build: symbol lookup error: /xxx/target/debug/build/torch-sys-19553a5e993180b5/build-script-build: undefined symbol: EVP_PKEY_get_id, version OPENSSL_3.0.0

Thanks, 
Jake Kalstad

**Comment by JakeKalstad** [comment]
I was able to get things to compile by getting into the schopin/openssl-3 repo and updating openssl

`sudo add-apt-repository ppa:schopin/openssl-3.0.0`
`sudo apt-get update`
