### ISSUE TITLE
fresh install rust-bert v0.16.0 fail 

### ISSUE THREAD

**Issue by remotejob** [guillaume-be/rust-bert#190]
I try install rust-bert v0.16.0 
libtorch-shared-with-deps-1.9.0%2Bcpu.zip
But compilation unsuccessful 
help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified

Enveroment:
Ubuntu 20.04.3 LTS
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
rustc 1.56.0

Compiling rust-bert v0.16.0
error: linking with `cc` failed: exit status: 1

  = note: /usr/bin/ld: /tmp/cargo-installzHNBYq/release/deps/libtorch_sys-e57768b55c383b2a.rlib(torch_api.o): in function `caffe2::TypeMeta::fromScalarType(c10::ScalarType)':
          torch_api.cpp:(.text._ZN6caffe28TypeMeta14fromScalarTypeEN3c1010ScalarTypeE[_ZN6caffe28TypeMeta14fromScalarTypeEN3c1010ScalarTypeE]+0xe0): undefined reference to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /tmp/cargo-installzHNBYq/release/deps/libtorch_sys-e57768b55c383b2a.rlib(torch_api.o): in function `c10::Device::validate()':
          torch_api.cpp:(.text._ZN3c106Device8validateEv[_ZN3c106Device8validateEv]+0xc1): undefined reference to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: torch_api.cpp:(.text._ZN3c106Device8validateEv[_ZN3c106Device8validateEv]+0x10a): undefined reference to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /tmp/cargo-installzHNBYq/release/deps/libtorch_sys-e57768b55c383b2a.rlib(torch_api.o): in function `c10::Type::createWithContained(std::vector<std::shared_ptr<c10::Type>, std::allocator<std::shared_ptr<c10::Type> > >) const':
          torch_api.cpp:(.text._ZNK3c104Type19createWithContainedESt6vectorISt10shared_ptrIS0_ESaIS3_EE[_ZNK3c104Type19createWithContainedESt6vectorISt10shared_ptrIS0_ESaIS3_EE]+0x74): undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /tmp/cargo-installzHNBYq/release/deps/libtorch_sys-e57768b55c383b2a.rlib(torch_api.o): in function `c10::IValue::toTuple() const &':
          torch_api.cpp:(.text._ZNKR3c106IValue7toTupleEv[_ZNKR3c106IValue7toTupleEv]+0xbc): undefined reference to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /tmp/cargo-installzHNBYq/release/deps/libtorch_sys-e57768b55c383b2a.rlib(torch_api.o): in function `c10::IValue::toIntList() const &':
          torch_api.cpp:(.text._ZNKR3c106IValue9toIntListEv[_ZNKR3c106IValue9toIntListEv]+0x6d): undefined reference to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /tmp/cargo-installzHNBYq/release/deps/libtorch_sys-e57768b55c383b2a.rlib(torch_api.o): in function `c10::IValue::toDoubleList() const &':
          torch_api.cpp:(.text._ZNKR3c106IValue12toDoubleListEv[_ZNKR3c106IValue12toDoubleListEv]+0x6d): undefined reference to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /tmp/cargo-installzHNBYq/release/deps/libtorch_sys-e57768b55c383b2a.rlib(torch_api.o): in function `c10::IValue::toBoolList() const &':
          torch_api.cpp:(.text._ZNKR3c106IValue10toBoolListEv[_ZNKR3c106IValue10toBoolListEv]+0x6d): undefined reference to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /tmp/cargo-installzHNBYq/release/deps/libtorch_sys-e57768b55c383b2a.rlib(torch_api.o): in function `c10::IValue::toTensorList() const &':
          torch_api.cpp:(.text._ZNKR3c106IValue12toTensorListEv[_ZNKR3c106IValue12toTensorListEv]+0x6d): undefined reference to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /tmp/cargo-installzHNBYq/release/deps/libtorch_sys-e57768b55c383b2a.rlib(torch_api.o):torch_api.cpp:(.text._ZNKR3c106IValue6toListEv[_ZNKR3c106IValue6toListEv]+0xb4): more undefined references to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
          /usr/bin/ld: /tmp/cargo-installzHNBYq/release/deps/libtorch_sys-e57768b55c383b2a.rlib(torch_api.o): in function `at_save_multi':
          torch_api.cpp:(.text.at_save_multi+0x2ae): undefined reference to `torch::serialize::OutputArchive::write(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, at::Tensor const&, bool)'
          /usr/bin/ld: torch_api.cpp:(.text.at_save_multi+0x30e): undefined reference to `torch::serialize::OutputArchive::save_to(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          collect2: error: ld returned 1 exit status

**Comment by guillaume-be** [comment]
Hello @remotejob ,

Are you trying to install `0.16.0` from _crates.io_ or building from this repository? The version deployed on _crates.io_ relies on `libtorch 1.9.0`, and should work with the set-up you mentioned. The version in this repository is not yet released, but depends on `tch 0.6.0` which uses `libtorch 1.10.0`. If you are building from this repository, please try downloading [libtorch 1.10](https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.10.0%2Bcpu.zip) instead.

**Comment by remotejob** [comment]
Finally, I made a compilation 
  Compiling torch-sys v0.5.0
   Compiling tch v0.5.0
   Compiling rust-bert v0.16.0

libtorch-shared-with-deps-1.9.0%2Bcpu.zip don't work for me (CPU ?)
so I use v1.9.0.zip what was automatically downloaded 

result work a little better compare to 
rust-bert = "0.15.1"
Unfortunately, I am new with Rust, can you give me hint
on how to use the version in this repository, I mean compile using libtorch 1.10.0
Thanks.

**Comment by remotejob** [comment]
OK it's not complicated !
rust-bert = {path = "/home/juno/repos/github.com/guillaume-be/rust-bert"}
Compiling tch v0.6.1
Compiling rust-bert v0.16.0 (/home/juno/repos/github.com/guillaume-be/rust-bert)

It's time to create a new model
Great! Thanks!!

**Comment by remotejob** [comment]
rust-bert/utils/convert_model.py --skip_embeddings reduce the size of the model but in my case, it does not increase production capacity
